# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore: 
      - 'README.md'
      # - '.github/workflows/*'
      - metadata.json
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        jq ".version" metadata.json
        echo test, and deploy your project. 
        ls -l
  artifakt:
    runs-on: ubuntu-latest
    steps:
    - name: preuzimanje
      run: |
        wget https://t7-live-ahsd8.nyc3.cdn.digitaloceanspaces.com/animalhumanesociety.org/files/styles/crop_16_9_960x540/flypub/media/image/2017-07/IMG_1090.jpg
        wget https://www.abc.net.au/news/image/1154232-3x2-700x467.jpg
    - name: paket
      uses: actions/upload-artifact@v1
      with:
        name: slike
        path: ./
  win-run:
    runs-on: [ self-hosted, ${{ matrix.lbl }} ]
    strategy:
      matrix:
        lbl: [r1, r3]
    needs: artifakt
    steps:
    - name: win masina
      run: |
        mkdir trci
    - name: preuzmi paket
      uses: actions/download-artifact@v1
      with:
        name: slike


