# This is a basic workflow to help you get started with Actions

name: NOTIFY_FILE_CHANGE

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    paths:
      - 'test-trigger.txt'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build" --data '{\"text\":\"Dokument je izmenjen\"}'
  send-notification:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      VER: 5
    steps:
    - uses: actions/checkout@v2
    - run: |
        git diff-tree --no-commit-id --name-only -r ${{ github.sha }} 
        # curl -X POST -H 'Content-type: application/json' --data '{"text":"Dokument je izmenjen"}' ${{ secrets.webhook_docs }} 
        echo `${{ github.run_number }} - $VER`

